Activation Functions

In [1]:
import math

In [2]:
def sigmoid(x) :
    return 1 / (1 + math.exp(-x))

In [11]:
sigmoid(100)

1.0

In [12]:
def tanh(x) :
    return (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))

In [31]:
tanh(19)

1.0

In [32]:
def relu(x) :
    return max(0, x)

In [37]:
relu(100)

100

In [38]:
def leaky_relu(x) :
    return max(0.1 * x, x)

In [41]:
leaky_relu(10)

10

Derivates

In [ ]:
# y = m1 * x1 + m2 * x2^2 + m3 * x2^3 + c

y = m1 * x1 + m2 * x2 * x2 + m3 * x3 * x3 * x3 + c

dy = dx (m1 * x1 + m2 * x2 * x2 + m3 * x3 * x3 * x3 + c)

y = m1 + 2m2 * x2 + 3m3 * x3 * x3 + 1

slope = dy / dx
slope = y / (m1 * x1 + m2 * x2 * x2 + m3 * x3 * x3 * x3 + c)


Matrices

In [42]:
import numpy as np

In [43]:
revenue = np.array([[180, 200, 220],[24, 36, 40], [12, 18, 20]])
expenses = np.array([[80, 90, 100],[10, 16, 20], [8, 10, 10]])

In [44]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [45]:
price_per_unit = np.array([1000, 400, 1200])
units = np.array([[30,40,50], [5, 10, 15], [2,5,7]])

In [46]:
total_earnings = price_per_unit * units
total_earnings

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [49]:
np.dot(price_per_unit, units)

array([34400, 50000, 64400])

Loss values & cost function

In [50]:
import numpy as np

In [57]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [62]:
def mae(y_true, y_predicted) :
    total_error = 0
    for yt, yp in zip(y_true, y_predicted) :
        total_error += abs(yt - yp)
        print("total error", total_error)
        mae = total_error / len(y_true)
        print("Mae", mae)
        return mae

In [63]:
mae(y_true, y_predicted)

total error 0.7
Mae 0.13999999999999999


0.13999999999999999

In [65]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [75]:
np.log([0.00000000000000000000000000000000000000000001])

array([-101.31374409])

In [76]:
epsilon = 1e-15

In [79]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [80]:
y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [82]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [83]:
np.log(y_predicted)

C:\Users\Aliasger B\AppData\Local\Temp\ipykernel_4316\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [84]:
-np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

17.2696280766844

In [88]:
def log_loss(y_true, y_predicted) :
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

In [89]:
log_loss(y_true, y_predicted)

17.2696280766844